### PR TITLE
review-only: bart's merge of anthony's code against latest arcbees

### PR DESCRIPTION
**Pull request by ewolk**
@bartmoc

@calcacuervo @okorokhina @cristianmiranda @dmazuruk @vwjugow

### CODE REVIEW

**Comment by ewolk** [comment]
(bart, feel free to force push this to master whenever you like)

**Comment by okorokhina** [comment]
@bartmoc Bart, have you checked the X-s for providers fields appears - you seems to did what I did but in my PR but in a different manner. Are they on board?

**Comment by bartmoc** [comment]
Yes, it's in this PR https://github.com/lillegroup/escribehost/pull/1457 ,
the cross is already there.

**Comment by okorokhina** [comment]
Nope, crosses can not be there until I merge my PR. The one you refer to is merged and here's no crosses:
screen shot 2016-04-13 at 05 36 12
Testing my esh PR with your chosen build.

**Comment by vwjugow** [comment]
looks good

**Pull request closed without merging**
